declare global {
    namespace JSX {
        type Element =
            | LiveComponentDescriptor
            | ElementDescriptor
            | VirtualNode<any>
            | null
            | false;

        interface ElementChildrenAttribute {
            children: {};
        }

        type EventHandler<E extends Event = Event> = (
            self: ComponentSelf,
            event: E
        ) => void;

        interface SVGPresentationAttributes {
            fill?: string;
            fillOpacity?: number | string;
            fillRule?: "nonzero" | "evenodd" | "inherit";
            stroke?: string;
            strokeOpacity?: number | string;
            strokeWidth?: number | string;
            strokeLinecap?: "butt" | "round" | "square" | "inherit";
            strokeLinejoin?: "miter" | "round" | "bevel" | "inherit";
            strokeDasharray?: string | number;
            strokeDashoffset?: number | string;
            strokeMiterlimit?: number;
            opacity?: number | string;
            visibility?: "visible" | "hidden" | "collapse" | "inherit";
            display?: string;
            overflow?: string;
            transform?: string;
            clipPath?: string;
            clipRule?: "nonzero" | "evenodd" | "inherit";
            mask?: string;
            filter?: string;
            color?: string;
            shapeRendering?: string;
            textRendering?: string;
            imageRendering?: string;
            colorInterpolation?: string;
            colorRendering?: string;
            fontFamily?: string;
            fontSize?: number | string;
            fontStyle?: string;
            fontWeight?: number | string;
            letterSpacing?: number | string;
            wordSpacing?: number | string;
            textDecoration?: string;
            dominantBaseline?: string;
            alignmentBaseline?: string;
            baselineShift?: string;
            direction?: string;
            writingMode?: string;
            unicodeBidi?: string;
            vectorEffect?: string;
            pointerEvents?: string;
            cursor?: string;
            paintOrder?: string;
        }

        interface SVGAnimationAttributes {
            attributeName?: string;
            attributeType?: string;
            from?: string | number;
            to?: string | number;
            by?: string | number;
            values?: string;
            calcMode?: string;
            keyTimes?: string;
            keySplines?: string;
            begin?: string;
            end?: string;
            dur?: string;
            min?: string;
            max?: string;
            restart?: string;
            repeatCount?: string | number;
            repeatDur?: string;
            fill?: "freeze" | "remove";
            additive?: "sum" | "replace";
            accumulate?: "sum" | "none";
        }

        interface EventHandlers {
            onClick?: EventHandler<MouseEvent>;
            onDblClick?: EventHandler<MouseEvent>;
            onMouseDown?: EventHandler<MouseEvent>;
            onMouseUp?: EventHandler<MouseEvent>;
            onMouseEnter?: EventHandler<MouseEvent>;
            onMouseLeave?: EventHandler<MouseEvent>;
            onMouseMove?: EventHandler<MouseEvent>;
            onMouseOver?: EventHandler<MouseEvent>;
            onMouseOut?: EventHandler<MouseEvent>;
            onContextMenu?: EventHandler<MouseEvent>;
            onKeyDown?: EventHandler<KeyboardEvent>;
            onKeyUp?: EventHandler<KeyboardEvent>;
            onKeyPress?: EventHandler<KeyboardEvent>;
            onChange?: EventHandler<Event>;
            onInput?: EventHandler<InputEvent>;
            onFocus?: EventHandler<FocusEvent>;
            onBlur?: EventHandler<FocusEvent>;
            onFocusIn?: EventHandler<FocusEvent>;
            onFocusOut?: EventHandler<FocusEvent>;
            onSubmit?: EventHandler<SubmitEvent>;
            onReset?: EventHandler<Event>;
            onScroll?: EventHandler<Event>;
            onWheel?: EventHandler<WheelEvent>;
            onSelect?: EventHandler<Event>;
            onLoad?: EventHandler<Event>;
            onError?: EventHandler<Event>;
            onDragStart?: EventHandler<DragEvent>;
            onDrag?: EventHandler<DragEvent>;
            onDragEnd?: EventHandler<DragEvent>;
            onDragOver?: EventHandler<DragEvent>;
            onDragEnter?: EventHandler<DragEvent>;
            onDragLeave?: EventHandler<DragEvent>;
            onDrop?: EventHandler<DragEvent>;
            onPointerDown?: EventHandler<PointerEvent>;
            onPointerUp?: EventHandler<PointerEvent>;
            onPointerMove?: EventHandler<PointerEvent>;
            onPointerEnter?: EventHandler<PointerEvent>;
            onPointerLeave?: EventHandler<PointerEvent>;
            onPointerCancel?: EventHandler<PointerEvent>;
            onPointerOver?: EventHandler<PointerEvent>;
            onPointerOut?: EventHandler<PointerEvent>;
            onTouchStart?: EventHandler<TouchEvent>;
            onTouchEnd?: EventHandler<TouchEvent>;
            onTouchMove?: EventHandler<TouchEvent>;
            onTouchCancel?: EventHandler<TouchEvent>;
            onTransitionEnd?: EventHandler<TransitionEvent>;
            onTransitionStart?: EventHandler<TransitionEvent>;
            onAnimationStart?: EventHandler<AnimationEvent>;
            onAnimationEnd?: EventHandler<AnimationEvent>;
            onAnimationIteration?: EventHandler<AnimationEvent>;
            onCopy?: EventHandler<ClipboardEvent>;
            onCut?: EventHandler<ClipboardEvent>;
            onPaste?: EventHandler<ClipboardEvent>;
        }

        interface CommonAttributes extends EventHandlers {
            id?: string;
            class?: string;
            className?: string;
            style?: string | Partial<CSSStyleDeclaration>;
            tabIndex?: number;
            title?: string;
            lang?: string;
            dir?: "ltr" | "rtl" | "auto";
            hidden?: boolean;
            draggable?: boolean | "true" | "false";
            contentEditable?: boolean | "true" | "false" | "inherit";
            spellCheck?: boolean;
            role?: string;
            slot?: string;
            part?: string;
            exportParts?: string;
            inert?: boolean;
            popover?: "" | "auto" | "manual";
            children?: Element | Element[] | string | number | boolean | null | undefined;
            key?: string | number;
            ref?: ((el: globalThis.Element) => void) | { current: globalThis.Element | null };
            [key: `data-${string}`]: string | undefined;
            [key: `aria-${string}`]: string | boolean | number | undefined;
        }

        type IntrinsicElements = {
            html:        CommonAttributes & { lang?: string; manifest?: string };
            head:        CommonAttributes;
            title:       CommonAttributes;
            base:        CommonAttributes & { href?: string; target?: string };
            link:        CommonAttributes & { rel?: string; href?: string; type?: string; media?: string; crossOrigin?: string; integrity?: string; referrerPolicy?: string; as?: string; disabled?: boolean };
            meta:        CommonAttributes & { name?: string; content?: string; httpEquiv?: string; charset?: string; property?: string };
            style:       CommonAttributes & { media?: string };
            body:        CommonAttributes;
            article:     CommonAttributes;
            section:     CommonAttributes;
            nav:         CommonAttributes;
            aside:       CommonAttributes;
            h1:          CommonAttributes;
            h2:          CommonAttributes;
            h3:          CommonAttributes;
            h4:          CommonAttributes;
            h5:          CommonAttributes;
            h6:          CommonAttributes;
            header:      CommonAttributes;
            footer:      CommonAttributes;
            address:     CommonAttributes;
            main:        CommonAttributes;
            p:           CommonAttributes;
            hr:          CommonAttributes;
            pre:         CommonAttributes;
            blockquote:  CommonAttributes & { cite?: string };
            ol:          CommonAttributes & { reversed?: boolean; start?: number; type?: string };
            ul:          CommonAttributes;
            li:          CommonAttributes & { value?: number };
            dl:          CommonAttributes;
            dt:          CommonAttributes;
            dd:          CommonAttributes;
            figure:      CommonAttributes;
            figcaption:  CommonAttributes;
            div:         CommonAttributes;
            a:           CommonAttributes & { href?: string; target?: string; rel?: string; download?: string | boolean; hrefLang?: string; type?: string; referrerPolicy?: string };
            em:          CommonAttributes;
            strong:      CommonAttributes;
            small:       CommonAttributes;
            s:           CommonAttributes;
            cite:        CommonAttributes;
            q:           CommonAttributes & { cite?: string };
            dfn:         CommonAttributes;
            abbr:        CommonAttributes;
            ruby:        CommonAttributes;
            rt:          CommonAttributes;
            rp:          CommonAttributes;
            data:        CommonAttributes & { value?: string };
            time:        CommonAttributes & { dateTime?: string };
            code:        CommonAttributes;
            kbd:         CommonAttributes;
            samp:        CommonAttributes;
            sub:         CommonAttributes;
            sup:         CommonAttributes;
            i:           CommonAttributes;
            b:           CommonAttributes;
            u:           CommonAttributes;
            mark:        CommonAttributes;
            bdi:         CommonAttributes;
            bdo:         CommonAttributes & { dir?: "ltr" | "rtl" };
            span:        CommonAttributes;
            br:          CommonAttributes;
            wbr:         CommonAttributes;
            ins:         CommonAttributes & { cite?: string; dateTime?: string };
            del:         CommonAttributes & { cite?: string; dateTime?: string };
            picture:     CommonAttributes;
            source:      CommonAttributes & { src?: string; srcSet?: string; sizes?: string; media?: string; type?: string; width?: number; height?: number };
            img:         CommonAttributes & { src?: string; alt?: string; width?: number | string; height?: number | string; loading?: "eager" | "lazy"; decoding?: "auto" | "sync" | "async"; crossOrigin?: string; referrerPolicy?: string; srcSet?: string; sizes?: string; useMap?: string; isMap?: boolean };
            iframe:      CommonAttributes & { src?: string; srcdoc?: string; name?: string; allow?: string; allowFullScreen?: boolean; width?: number | string; height?: number | string; loading?: "eager" | "lazy"; referrerPolicy?: string; sandbox?: string };
            embed:       CommonAttributes & { src?: string; type?: string; width?: number | string; height?: number | string };
            object:      CommonAttributes & { data?: string; type?: string; name?: string; width?: number | string; height?: number | string };
            video:       CommonAttributes & { src?: string; controls?: boolean; autoPlay?: boolean; loop?: boolean; muted?: boolean; preload?: string; poster?: string; width?: number | string; height?: number | string; playsInline?: boolean };
            audio:       CommonAttributes & { src?: string; controls?: boolean; autoPlay?: boolean; loop?: boolean; muted?: boolean; preload?: string };
            track:       CommonAttributes & { kind?: string; src?: string; srcLang?: string; label?: string; default?: boolean };
            map:         CommonAttributes & { name?: string };
            area:        CommonAttributes & { alt?: string; coords?: string; shape?: string; href?: string; target?: string; rel?: string };
            table:       CommonAttributes;
            caption:     CommonAttributes;
            colgroup:    CommonAttributes & { span?: number };
            col:         CommonAttributes & { span?: number };
            tbody:       CommonAttributes;
            thead:       CommonAttributes;
            tfoot:       CommonAttributes;
            tr:          CommonAttributes;
            td:          CommonAttributes & { colSpan?: number; rowSpan?: number; headers?: string };
            th:          CommonAttributes & { colSpan?: number; rowSpan?: number; headers?: string; scope?: "col" | "row" | "colgroup" | "rowgroup"; abbr?: string };
            form:        CommonAttributes & { action?: string; method?: string; encType?: string; target?: string; noValidate?: boolean; autoComplete?: string; name?: string };
            label:       CommonAttributes & { for?: string; htmlFor?: string };
            input:       CommonAttributes & { type?: string; name?: string; value?: string | number; defaultValue?: string; placeholder?: string; disabled?: boolean; required?: boolean; readOnly?: boolean; checked?: boolean; defaultChecked?: boolean; min?: string | number; max?: string | number; step?: string | number; multiple?: boolean; accept?: string; autoComplete?: string; autoFocus?: boolean; form?: string; list?: string; maxLength?: number; minLength?: number; pattern?: string; size?: number; src?: string; alt?: string; width?: number; height?: number; capture?: string };
            button:      CommonAttributes & { type?: "button" | "submit" | "reset"; disabled?: boolean; name?: string; value?: string; form?: string; formAction?: string; formMethod?: string; formEncType?: string; formTarget?: string; formNoValidate?: boolean; autoFocus?: boolean };
            select:      CommonAttributes & { name?: string; value?: string; multiple?: boolean; disabled?: boolean; required?: boolean; size?: number; autoComplete?: string; autoFocus?: boolean; form?: string };
            datalist:    CommonAttributes;
            optgroup:    CommonAttributes & { label?: string; disabled?: boolean };
            option:      CommonAttributes & { value?: string; label?: string; disabled?: boolean; selected?: boolean };
            textarea:    CommonAttributes & { name?: string; value?: string; placeholder?: string; disabled?: boolean; required?: boolean; readOnly?: boolean; rows?: number; cols?: number; maxLength?: number; minLength?: number; wrap?: string; autoComplete?: string; autoFocus?: boolean; form?: string };
            output:      CommonAttributes & { for?: string; htmlFor?: string; form?: string; name?: string };
            progress:    CommonAttributes & { value?: number; max?: number };
            meter:       CommonAttributes & { value?: number; min?: number; max?: number; low?: number; high?: number; optimum?: number };
            fieldset:    CommonAttributes & { disabled?: boolean; form?: string; name?: string };
            legend:      CommonAttributes;
            details:     CommonAttributes & { open?: boolean };
            summary:     CommonAttributes;
            dialog:      CommonAttributes & { open?: boolean };
            script:      CommonAttributes & { src?: string; type?: string; async?: boolean; defer?: boolean; crossOrigin?: string; integrity?: string; noModule?: boolean; referrerPolicy?: string };
            noscript:    CommonAttributes;
            template:    CommonAttributes;
            slot:        CommonAttributes & { name?: string };
            canvas:      CommonAttributes & { width?: number | string; height?: number | string };
            svg:         CommonAttributes & SVGPresentationAttributes & { xmlns?: string; viewBox?: string; width?: number | string; height?: number | string; preserveAspectRatio?: string };
            g:           CommonAttributes & SVGPresentationAttributes;
            defs:        CommonAttributes;
            desc:        CommonAttributes;
            symbol:      CommonAttributes & { viewBox?: string; x?: number | string; y?: number | string; width?: number | string; height?: number | string };
            use:         CommonAttributes & { href?: string; x?: number | string; y?: number | string; width?: number | string; height?: number | string };
            image:       CommonAttributes & SVGPresentationAttributes & { href?: string; x?: number | string; y?: number | string; width?: number | string; height?: number | string; preserveAspectRatio?: string };
            switch:      CommonAttributes;
            path:        CommonAttributes & SVGPresentationAttributes & { d?: string; pathLength?: number };
            rect:        CommonAttributes & SVGPresentationAttributes & { x?: number | string; y?: number | string; width?: number | string; height?: number | string; rx?: number | string; ry?: number | string };
            circle:      CommonAttributes & SVGPresentationAttributes & { cx?: number | string; cy?: number | string; r?: number | string };
            ellipse:     CommonAttributes & SVGPresentationAttributes & { cx?: number | string; cy?: number | string; rx?: number | string; ry?: number | string };
            line:        CommonAttributes & SVGPresentationAttributes & { x1?: number | string; y1?: number | string; x2?: number | string; y2?: number | string };
            polyline:    CommonAttributes & SVGPresentationAttributes & { points?: string };
            polygon:     CommonAttributes & SVGPresentationAttributes & { points?: string };
            text:        CommonAttributes & SVGPresentationAttributes & { x?: number | string; y?: number | string; dx?: number | string; dy?: number | string; textAnchor?: string; dominantBaseline?: string; lengthAdjust?: string; textLength?: number | string };
            tspan:       CommonAttributes & SVGPresentationAttributes & { x?: number | string; y?: number | string; dx?: number | string; dy?: number | string };
            textPath:    CommonAttributes & SVGPresentationAttributes & { href?: string; startOffset?: number | string; method?: string; spacing?: string };
            marker:          CommonAttributes & { markerWidth?: number | string; markerHeight?: number | string; refX?: number | string; refY?: number | string; orient?: string; markerUnits?: string; viewBox?: string; preserveAspectRatio?: string };
            pattern:         CommonAttributes & { x?: number | string; y?: number | string; width?: number | string; height?: number | string; patternUnits?: string; patternTransform?: string; viewBox?: string; href?: string };
            mask:            CommonAttributes & { x?: number | string; y?: number | string; width?: number | string; height?: number | string; maskUnits?: string };
            clipPath:        CommonAttributes & { clipPathUnits?: string };
            linearGradient:  CommonAttributes & { x1?: number | string; y1?: number | string; x2?: number | string; y2?: number | string; gradientUnits?: string; gradientTransform?: string; spreadMethod?: string; href?: string };
            radialGradient:  CommonAttributes & { cx?: number | string; cy?: number | string; r?: number | string; fx?: number | string; fy?: number | string; gradientUnits?: string; gradientTransform?: string; spreadMethod?: string; href?: string };
            stop:            CommonAttributes & { offset?: number | string; stopColor?: string; stopOpacity?: number };
            filter:              CommonAttributes & { x?: number | string; y?: number | string; width?: number | string; height?: number | string; filterUnits?: string; primitiveUnits?: string };
            feBlend:             CommonAttributes & { in?: string; in2?: string; mode?: string; result?: string };
            feColorMatrix:       CommonAttributes & { in?: string; type?: string; values?: string; result?: string };
            feComponentTransfer: CommonAttributes & { in?: string; result?: string };
            feComposite:         CommonAttributes & { in?: string; in2?: string; operator?: string; k1?: number; k2?: number; k3?: number; k4?: number; result?: string };
            feConvolveMatrix:    CommonAttributes & { in?: string; order?: string; kernelMatrix?: string; divisor?: number; bias?: number; targetX?: number; targetY?: number; edgeMode?: string; preserveAlpha?: boolean; result?: string };
            feDiffuseLighting:   CommonAttributes & { in?: string; surfaceScale?: number; diffuseConstant?: number; result?: string };
            feDisplacementMap:   CommonAttributes & { in?: string; in2?: string; scale?: number; xChannelSelector?: string; yChannelSelector?: string; result?: string };
            feDistantLight:      CommonAttributes & { azimuth?: number; elevation?: number };
            feDropShadow:        CommonAttributes & { dx?: number; dy?: number; stdDeviation?: number | string; floodColor?: string; floodOpacity?: number; result?: string };
            feFlood:             CommonAttributes & { floodColor?: string; floodOpacity?: number; result?: string };
            feFuncA:             CommonAttributes & { type?: string; tableValues?: string; slope?: number; intercept?: number; amplitude?: number; exponent?: number; offset?: number };
            feFuncB:             CommonAttributes & { type?: string; tableValues?: string; slope?: number; intercept?: number; amplitude?: number; exponent?: number; offset?: number };
            feFuncG:             CommonAttributes & { type?: string; tableValues?: string; slope?: number; intercept?: number; amplitude?: number; exponent?: number; offset?: number };
            feFuncR:             CommonAttributes & { type?: string; tableValues?: string; slope?: number; intercept?: number; amplitude?: number; exponent?: number; offset?: number };
            feGaussianBlur:      CommonAttributes & { in?: string; stdDeviation?: number | string; edgeMode?: string; result?: string };
            feImage:             CommonAttributes & { href?: string; preserveAspectRatio?: string; result?: string };
            feMerge:             CommonAttributes & { result?: string };
            feMergeNode:         CommonAttributes & { in?: string };
            feMorphology:        CommonAttributes & { in?: string; operator?: string; radius?: number | string; result?: string };
            feOffset:            CommonAttributes & { in?: string; dx?: number; dy?: number; result?: string };
            fePointLight:        CommonAttributes & { x?: number; y?: number; z?: number };
            feSpecularLighting:  CommonAttributes & { in?: string; surfaceScale?: number; specularConstant?: number; specularExponent?: number; result?: string };
            feSpotLight:         CommonAttributes & { x?: number; y?: number; z?: number; pointsAtX?: number; pointsAtY?: number; pointsAtZ?: number; specularExponent?: number; limitingConeAngle?: number };
            feTile:              CommonAttributes & { in?: string; result?: string };
            feTurbulence:        CommonAttributes & { baseFrequency?: number | string; numOctaves?: number; seed?: number; stitchTiles?: string; type?: string; result?: string };
            foreignObject: CommonAttributes & { x?: number | string; y?: number | string; width?: number | string; height?: number | string };
            view:          CommonAttributes & { viewBox?: string; preserveAspectRatio?: string };
            animate:           CommonAttributes & SVGAnimationAttributes;
            animateMotion:     CommonAttributes & SVGAnimationAttributes & { path?: string; keyPoints?: string; rotate?: string | number; origin?: string };
            animateTransform:  CommonAttributes & SVGAnimationAttributes & { attributeName?: string; type?: string };
            set:               CommonAttributes & { attributeName?: string; to?: string };
            mpath:             CommonAttributes & { href?: string };
            math:          CommonAttributes & { display?: "block" | "inline" };
            maction:       CommonAttributes & { actiontype?: string; selection?: number };
            mi:            CommonAttributes & { mathvariant?: string };
            mmultiscripts: CommonAttributes;
            mn:            CommonAttributes;
            mo:            CommonAttributes & { form?: string; fence?: boolean; separator?: boolean; lspace?: string; rspace?: string; stretchy?: boolean; symmetric?: boolean; maxsize?: string; minsize?: string; largeop?: boolean; movablelimits?: boolean };
            mover:         CommonAttributes & { accent?: boolean };
            mpadded:       CommonAttributes & { width?: string; height?: string; depth?: string; lspace?: string; voffset?: string };
            mphantom:      CommonAttributes;
            mroot:         CommonAttributes;
            mrow:          CommonAttributes;
            ms:            CommonAttributes & { lquote?: string; rquote?: string };
            mspace:        CommonAttributes & { width?: string; height?: string; depth?: string };
            msqrt:         CommonAttributes;
            mstyle:        CommonAttributes;
            msub:          CommonAttributes;
            msubsup:       CommonAttributes;
            msup:          CommonAttributes;
            mtable:        CommonAttributes & { align?: string; columnalign?: string; columnspacing?: string; rowspacing?: string; frame?: string; framespacing?: string };
            mtd:           CommonAttributes & { columnspan?: number; rowspan?: number; columnalign?: string; rowalign?: string };
            mtext:         CommonAttributes & { mathvariant?: string };
            mtr:           CommonAttributes & { columnalign?: string; rowalign?: string };
            munder:        CommonAttributes & { accentunder?: boolean };
            munderover:    CommonAttributes & { accent?: boolean; accentunder?: boolean };
            semantics:     CommonAttributes;
            annotation:    CommonAttributes & { encoding?: string };
            "annotation-xml": CommonAttributes & { encoding?: string };
        };

    }
    
    function Fragment(props: { children?: JSX.Element | JSX.Element[] | string | number | boolean | null | undefined }): JSX.Element | null;
}

export {};