/**
 * This file contains the functions used by compiler_process to compile pages.
 */


import path from "path";
import crypto from "crypto";
import { AnyElement, EleganceElement, ElementOptions, invalidElementError, SpecialElementOption } from "../elements/element";
import { Dirent, existsSync, mkdirSync, readdirSync, readFileSync, writeFile, writeFileSync } from "fs";
import esbuild, { transform } from "esbuild";
import { invalidPageError, PageConstructor, PageExports, PageInformation, PageMetadataConstructor } from "../server/page";
import { invalidLayoutError, LayoutExports, LayoutInformation } from "../server/layout";

// make sure to hook every element builder into the global scope
import { allElements } from "../elements/element_list";
import { isAsyncFunction } from "util/types";
import { EventListener } from "../client/eventListener";
import { Observer } from "../client/observer";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

Object.assign(globalThis, allElements);

const clientTsPath = path.join(__dirname, "..", "client", "runtime.ts");

/** Context of a page that is currently being compiled. */
type PageCompilationContext = {
    /** The slash starting relative pathname (relative to pagesDirectory) of this page. */
    pathname: string,

    /** 
     * An id counter starting from 0, that is incremented once per generateID() call, 
     * and is used in conjunction with the pathname to generate unique static IDs (order-dependent) 
     */
    idCounter: number,
    usedHashes: string[],
};

/** Context of a layout that is currently being compiled. */
type LayoutCompilationContext = {
    /** The slash starting relative pathname (relative to pagesDirectory) of this layout. */
    pathname: string,

    /** 
     * An id counter starting from 0, that is incremented once per generateID() call, 
     * and is used in conjunction with the pathname to generate unique static IDs (order-dependent) 
     */
    idCounter: number,
    usedHashes: string[],
};

type CompilerOptions = {
    pagesDirectory: string;

    outputDirectory: string;
};

type CompiledLayout = {
    /** Compiled result of the layoutConstructor */
    layoutHTMLStart: string,
    layoutHTMLEnd: string,

    /** Client data tokens generated by the layoutConstructor & layoutMetadataConstructor during it's compilation. */
    specialElementOptions: { optionName: string, optionValue: SpecialElementOption }[],

    /** Compiled result of the layoutMetadataConstructor */
    layoutMetadataHTML: string,
};

type CompiledPage = {
    pageHTML: string,
};

/** The result of turning an element into a string and extracting any special options from it. */
type SerializationResult = { serializedElement: string, specialElementOptions: { optionName: string, optionValue: SpecialElementOption }[] };

let compilerOptions: CompilerOptions;

function getDistDir() {
    const fullPath = path.join(compilerOptions.outputDirectory, "DIST");

    if (existsSync(fullPath) === false) {
        mkdirSync(fullPath, { recursive: true, })
    }

    return fullPath;
}

function setCompilerOptions(newOptions: CompilerOptions) {
    newOptions.pagesDirectory = path.resolve(newOptions.pagesDirectory);
    newOptions.outputDirectory = path.resolve(newOptions.outputDirectory);

    if (existsSync(newOptions.pagesDirectory) === false) {
        throw new Error(newOptions.pagesDirectory + " does not exist, and thus cannot be used as the pagesDirectory.");
    }

    if (existsSync(newOptions.outputDirectory) === false) {
        mkdirSync(newOptions.outputDirectory, { recursive: true, })
    }

    compilerOptions = newOptions;
}

/** 
 * Generate a stable, page-specific & order-dependent unique-identifier. 
 * NOTE: This function will throw if it fails to generate a hash after 100+ attempts.
 * However, this is not technically possible.
 */
function generateId(compilationContext: PageCompilationContext): string {
    let id: string;
    let tries = 0;

    while (true) {
        compilationContext.idCounter += 1;

        id = crypto
            .createHash('sha256')
            .update(compilationContext.pathname + ':' + compilationContext.idCounter.toString())
            .digest('base64url')
            .slice(0, 11); // 66 bits of entropy

        if (!compilationContext.usedHashes.includes(id)) {
            break;
        }

        tries += 1;

        if (tries > 100) {
            throw new Error("Failed to generate a unique id after 100+ attempts");
        }
    }
    
    compilationContext.usedHashes.push(id);

    return id;
}

function generateLayoutId(layoutInformation: LayoutInformation): string {
    return crypto
        .createHash('sha256')
        .update(layoutInformation.pathname)
        .digest('base64url')
        .slice(0, 11); // 66 bits of entropy
}

function internalCompilerError(reason: string) {
    return new Error(`The compiler has encountered an internal error.\n${reason}`);
}

/** Take any directory pathname, and make it into this format: /path */
function sanitizePathname(pathname: string = ""): string {
    if (!pathname) return "/";

    pathname = "/" + pathname;

    pathname = pathname.replace(/\/+/g, "/");

    if (pathname.length > 1 && pathname.endsWith("/")) {
        pathname = pathname.slice(0, -1);
    }

    return pathname;
}

function getElementKey(compilationContext: PageCompilationContext, element: EleganceElement<any>): string {
    if (element.key) return element.key;

    element.key = generateId(compilationContext);

    return element.key;
}

function generatePageCompilationContext(pathname: string): PageCompilationContext {
    pathname = sanitizePathname(pathname);

    return {
        pathname: pathname,
        idCounter: 0,
        usedHashes: [],
    };
}

function generateLayoutCompilationContext(pathname: string): LayoutCompilationContext {
    pathname = sanitizePathname(pathname);

    return {
        pathname: pathname,
        idCounter: 0,
        usedHashes: [],
    };
}

function serializeEleganceElement(
    compilationContext: PageCompilationContext,
    element: EleganceElement<any>
): SerializationResult {
    let serializedElement = "";
    let specialElementOptions: { optionName: string, optionValue: SpecialElementOption }[] = [];

    serializedElement += `<${element.tag}`;
    
    // Process options.
    {
        const options = Object.entries(element.options);

        if (options.length > 0) {
            for (const [optionName, optionValue] of options) {
                serializedElement += ` ${optionName}="${optionValue}"`;
            }
        }
    }

    serializedElement += ">";
    
    // Process children.
    {
        if (element.children === null) {

            return { serializedElement, specialElementOptions, };
        }

        if (element.children.length > 0) {
            for (const child of element.children) {
                const result = serializeElement(compilationContext, child)

                serializedElement += result.serializedElement;
                specialElementOptions.push(...result.specialElementOptions);
            }
        }
    }

    serializedElement += `</${element.tag}>`;

    return { serializedElement, specialElementOptions, };
}

function serializeElement(
    compilationContext: PageCompilationContext,
    element: AnyElement,
): SerializationResult {
    let serializedElement: string;
    let specialElementOptions: { optionName: string, optionValue: SpecialElementOption }[] = [];

    if (element === undefined || element === null) {
        throw invalidElementError(element, "Undefined and null are not valid elements.");
    }

    switch (typeof element) {
    case "object":
        if (Array.isArray(element)) {
            let serializedElements = "";

            for (const subElement of element) {
                const serializationResult = serializeElement(compilationContext, subElement);
                
                serializedElements += serializationResult.serializedElement;
                specialElementOptions.push(...serializationResult.specialElementOptions);
            }

            serializedElement = serializedElements;

            break;
        }

        if (element instanceof EleganceElement) {
            const entries = Object.entries(element.options);

            for (const [optionName, optionValue] of entries) {
                if (optionValue instanceof SpecialElementOption) {
                    optionValue.mutate(element, optionName);

                    specialElementOptions.push({ optionName, optionValue });
                }
            }

            const result = serializeEleganceElement(compilationContext, element);

            serializedElement = result.serializedElement;
            specialElementOptions.push(...result.specialElementOptions);

            break;
        }

        throw invalidElementError(element, "This element is an arbitrary object, and arbitrary objects are not valid children. Please make sure all elements are one of: EleganceElement, boolean, number, string or Array.")
    case "boolean":
        serializedElement = `${element}`;
        break;
    case "number":
        serializedElement = element.toString();
        break;
    case "string":
        serializedElement = element;
        break;
    default:
        throw invalidElementError(element, "The typeof of this element as not one of EleganceElement, boolean, number, string or Array. Please convert it into one of these types.");
    }

    return { serializedElement, specialElementOptions, };
}

async function generatePageDataScript(compilationContext: PageCompilationContext, specialElementOptions: { optionName: string, optionValue: SpecialElementOption }[]) {
    let dataScriptContent = `export const data = {`;

    {
        const eventListenerOptions = specialElementOptions.filter(seo => seo.optionValue instanceof EventListener);

        dataScriptContent += "eventListeners:[";
        for (const eventListenerOption of eventListenerOptions) {
            const eventListener = eventListenerOption.optionValue;
            const optionName = eventListenerOption.optionName;

            const result = eventListener.serialize(optionName);
            dataScriptContent += `${result},`;
        }
        dataScriptContent += "],";

        const observerOptions = specialElementOptions.filter(seo => seo.optionValue instanceof Observer);

        dataScriptContent += "observers:[";
        for (const observerOption of observerOptions) {
            const observer = observerOption.optionValue;
            const optionName = observerOption.optionName;

            const result = observer.serialize(optionName);
            dataScriptContent += `${result},`;
        }
        dataScriptContent += "]";
    }

    dataScriptContent += "};\n";

    const transformedResult = await esbuild.transform(dataScriptContent, { minify: true, });
    dataScriptContent = transformedResult.code;

    let dataScript = `<script data-hook="true" data-pathname="${compilationContext.pathname}" type="text/plain">${dataScriptContent}</script>`;
    let dataLoaderScript = `<script>
            const dataScript = document.querySelector('[data-hook="true"][data-pathname="${compilationContext.pathname}"][type="text/plain"');
            const text = dataScript.textContent;
            dataScript.remove();
            const blob = new Blob([text], { type: 'text/javascript' });
            const url = URL.createObjectURL(blob);
            
            const script = document.createElement("script");
            script.src = url;
            script.type = "module";
            script.setAttribute("data-page", "true");
            script.setAttribute("data-pathname", "${compilationContext.pathname}");
            
            document.head.appendChild(script);
            
            document.currentScript.remove();
        </script>`;

    return dataScript + dataLoaderScript;
}

/** 
 * Go through a directory, including all it's subdirectories, 
 * and call callback() for each file.
 */
async function walkDirectory(fullPath: string, callback: (file: Dirent) => Promise<void>) {
    const stack: Dirent[] = [];

    stack.push(...readdirSync(fullPath, { withFileTypes: true, }));

    while (true) {
        const entry = stack.pop();
        if (!entry) break;

        if (entry.isDirectory()) {
            const fullPath = path.join(entry.parentPath, entry.name);

            stack.push(...readdirSync(fullPath, { withFileTypes: true, }));

            continue;
        }

        if (!entry.isFile()) continue;

        await callback(entry);
    }
}

/** 
 * Get a structured, validated and formatted version of the exports of a page.ts file
 * This file *should* be the first thing that imports a page.
 */
async function getPageExports(modulePath: string): Promise<PageExports> {
    const rawExports = await import("file://" + modulePath);

    let isDynamic = rawExports?.isDynamic === true

    const pageConstructor = rawExports.page;
    {
        if (typeof pageConstructor !== "function") {
            throw invalidPageError(compilerOptions, modulePath, "The type of the export \"page\" is not a function, and is instead of type: " + typeof pageConstructor);
        }
    }

    const pageMetadataConstructor = rawExports.metadata;
    {
        if (typeof pageMetadataConstructor !== "function") {
            throw invalidPageError(compilerOptions, modulePath, "The type of the export \"metadata\" is not a function, and is instead of type: " + typeof pageMetadataConstructor);
        }
    }
    
    return {
        isDynamic,
        pageConstructor,
        pageMetadataConstructor,
    };
}

/** 
 * Get a structured, validated and formatted version of the exports of a layout.ts file
 * This file *should* be the first thing that imports a page.
 */
async function getLayoutExports(modulePath: string): Promise<LayoutExports> {
    const rawExports = await import("file://" + modulePath);

    let isDynamic = rawExports?.isDynamic === true

    const layoutConstructor = rawExports.layout;
    {
        if (typeof layoutConstructor !== "function") {
            throw invalidLayoutError(compilerOptions, modulePath, "The type of the export \"layout\" is not a function, and is instead of type: " + typeof layoutConstructor);
        }
    }

    const layoutMetadataConstructor = rawExports.metadata;
    {
        if (typeof layoutMetadataConstructor !== "function") {
            throw invalidLayoutError(compilerOptions, modulePath, "The type of the export \"metadata\" is not a function, and is instead of type: " + typeof layoutMetadataConstructor);
        }
    }
    
    return {
        isDynamic,
        layoutConstructor,
        layoutMetadataConstructor,
    };
}

async function getApplicablePageLayouts(allLayouts: Map<string, LayoutInformation>, pagePathname: string): Promise<LayoutInformation[]> {
    const pageLayouts: LayoutInformation[] = [];

    for (const [_, layoutInformation] of allLayouts.entries()) {
        const doesLayoutApply = pagePathname.startsWith(layoutInformation.pathname);

        if (!doesLayoutApply) continue;

        pageLayouts.push(layoutInformation);
    }

    pageLayouts.sort((a: LayoutInformation, b: LayoutInformation) => a.pathname.length - b.pathname.length);

    return pageLayouts;
}

async function gatherAllPages(allLayouts: Map<string, LayoutInformation>): Promise<Map<string, PageInformation>> {
    const pageMap = new Map();

    await walkDirectory(compilerOptions.pagesDirectory, async (file) => {
        if (file.name !== "page.ts") return;

        const fullPath = path.join(file.parentPath, file.name);
        const pathname = sanitizePathname(path.relative(compilerOptions.pagesDirectory, file.parentPath));

        const exports = await getPageExports(fullPath);
        const applicablePageLayouts = await getApplicablePageLayouts(allLayouts, pathname);

        const pageInformation: PageInformation = {
            modulePath: fullPath,
            exports: exports,
            pathname: pathname,
            applicableLayouts: applicablePageLayouts,
        };

        pageMap.set(pathname, pageInformation);
    })

    return pageMap;
}

async function gatherAllLayouts(): Promise<Map<string, LayoutInformation>> {
    const layoutMap = new Map();

    await walkDirectory(compilerOptions.pagesDirectory, async (file) => {
        if (file.name !== "layout.ts") return;

        const fullPath = path.join(file.parentPath, file.name);
        const pathname = sanitizePathname(path.relative(compilerOptions.pagesDirectory, file.parentPath));

        const exports = await getLayoutExports(fullPath);

        const layoutInformation: LayoutInformation = {
            modulePath: fullPath,
            exports: exports,
            pathname: pathname,
        };

        layoutMap.set(pathname, layoutInformation);
    })

    return layoutMap;
}

const compiledStaticLayouts = new Map<string, CompiledLayout>();
async function getCompiledLayout(layoutInformation: LayoutInformation, allLayouts: Map<string, LayoutInformation>): Promise<CompiledLayout> {
    if (layoutInformation.exports.isDynamic === true) {
        return await compileLayout(layoutInformation);
    }

    if (compiledStaticLayouts.has(layoutInformation.pathname)) {
        return compiledStaticLayouts.get(layoutInformation.pathname)!;
    }

    const compiledLayout = await compileLayout(layoutInformation);
    compiledStaticLayouts.set(layoutInformation.pathname, compiledLayout);

    return compiledLayout;
}

async function compilePageToDisk(
    allLayouts: Map<string, LayoutInformation>, 
    pageInformation: PageInformation
): Promise<void> {
    const compiledPage = await compilePage(allLayouts, pageInformation);
}

async function compilePage(
    allLayouts: Map<string, LayoutInformation>, 
    pageInformation: PageInformation
): Promise<CompiledPage> {
    const compilationContext = generatePageCompilationContext(pageInformation.pathname);

    const exports = pageInformation.exports;
    const pageConstructor = exports.pageConstructor;
    const pageMetadataConstructor = exports.pageMetadataConstructor;

    let pageRootElement: AnyElement;
    {
        if (isAsyncFunction(pageConstructor)) {
            pageRootElement = await pageConstructor();
        } else {
            pageRootElement = (pageConstructor() as AnyElement);
        }
    }

    let pageRootMetadataElement: AnyElement;
    {
        if (isAsyncFunction(pageMetadataConstructor)) {
            pageRootMetadataElement = await pageMetadataConstructor();
        } else {
            pageRootMetadataElement = (pageMetadataConstructor() as AnyElement);
        }
    }

    let pageSerializationResult: SerializationResult;
    let pageMetadataSerializationResult: SerializationResult;
    try {
        pageSerializationResult = serializeElement(compilationContext, pageRootElement);
        pageMetadataSerializationResult = serializeElement(compilationContext, pageRootMetadataElement);
    } catch(e) {
        console.error(`Failed to serialize the elements of a page with the pathname: "${pageInformation.pathname}"`);
        throw e;
    }

    const pageHTML = pageSerializationResult.serializedElement;
    const pageMetadataHTML = pageMetadataSerializationResult.serializedElement;

    let finalHTML: string = "<!DOCTYPE html>";

    // go through the layouts, and construct the end-stage page html
    if (pageInformation.applicableLayouts.length > 0) {
        const allSpecialElementOptions = [
            ...pageSerializationResult.specialElementOptions,
            ...pageMetadataSerializationResult.specialElementOptions,
        ];

        const rootLayout = pageInformation.applicableLayouts[0];
        const compiledRootLayout = await getCompiledLayout(rootLayout, allLayouts);

        const htmlTagIndex = compiledRootLayout.layoutHTMLStart.indexOf("<html");
        const htmlTagEndIndex = compiledRootLayout.layoutHTMLStart.indexOf(">");

        if (htmlTagIndex === -1 || htmlTagEndIndex === -1) {
            throw invalidLayoutError(compilerOptions, rootLayout.modulePath, "The root layout must start with an html() element.");
        }

        if (compiledRootLayout.layoutHTMLStart.includes("<body") === false) {
            throw invalidLayoutError(compilerOptions, rootLayout.modulePath, "The root layout must contain the body() element.");
        }

        const beforeHead = compiledRootLayout.layoutHTMLStart.substring(0, htmlTagEndIndex + 1);
        const afterHead = compiledRootLayout.layoutHTMLStart.substring(htmlTagEndIndex + 1);

        // gather the content of the head element, and inject it right after the <html> opening tag
        let headContent = "";
        {
            headContent += "<head>";

            for (const layoutInformation of pageInformation.applicableLayouts) {
                    const compiledLayout = await getCompiledLayout(layoutInformation, allLayouts);

                    headContent += compiledLayout.layoutMetadataHTML;

                    allSpecialElementOptions.push(...compiledLayout.specialElementOptions);
                }
                
                headContent += pageMetadataHTML

            headContent += "</head>";
        }

        finalHTML += beforeHead + headContent + afterHead;

        // skip the root layout, since we already added it in.
        for (let i = 1; i < pageInformation.applicableLayouts.length; i++) {
            const layoutInformation = pageInformation.applicableLayouts[i];

            const compiledLayout = await getCompiledLayout(layoutInformation, allLayouts);

            finalHTML += compiledLayout.layoutHTMLStart;
        }

        finalHTML += pageHTML

        let endString = "";

        for (const layoutInformation of [...pageInformation.applicableLayouts].reverse()) {
            const compiledLayout = await getCompiledLayout(layoutInformation, allLayouts);

            endString += compiledLayout.layoutHTMLEnd;
        }

        const htmlEndTagIndex = endString.indexOf("</body>");
        if (htmlEndTagIndex === -1) {
            throw internalCompilerError("Failed to find </body> tag whilst compiling a page");
        }

        const beforeEndTag = endString.substring(0, htmlEndTagIndex);
        const afterEndTag = endString.substring(htmlEndTagIndex);

        const pageDataScript = await generatePageDataScript(compilationContext, allSpecialElementOptions);
        finalHTML += beforeEndTag + pageDataScript + afterEndTag;


    } else {
        finalHTML += `<html lang="en-us">`;
            finalHTML += "<head>";
                finalHTML += pageMetadataHTML;
            finalHTML += "</head>";
            
            finalHTML += "<body>";
                finalHTML += pageHTML;

                const allSpecialElementOptions = [
                    ...pageSerializationResult.specialElementOptions, 
                    ...pageMetadataSerializationResult.specialElementOptions,
                ];

                const pageDataScript = await generatePageDataScript(compilationContext, allSpecialElementOptions);

                finalHTML += pageDataScript;
            finalHTML += "</body>";
        finalHTML += `</html>`;
    }

    const compiledPage = {
        pageHTML: finalHTML,
    };

    return compiledPage;
}

async function compileStaticPages(
    allLayouts: Map<string, LayoutInformation>, 
    allPages: Map<string, PageInformation>
): Promise<Map<string, CompiledPage>> {
    const compiledPages = new Map();

    for (const [pagePathname, pageInformation] of allPages) {
        if (pageInformation.exports.isDynamic === true) continue;

        const compiledPage = await compilePage(allLayouts, pageInformation);
        
        compiledPages.set(pagePathname, compiledPage);
    }

    return compiledPages;
}

async function compileLayoutToDisk(layoutInformation: LayoutInformation): Promise<void> {
    const compiledLayout = await compileLayout(layoutInformation);

    const directory = path.join(getDistDir(), layoutInformation.pathname);
    const htmlFullPath = path.join(directory, "layout.html");
    const htmlMetadataFullPath = path.join(directory, "layout_metadata.html");
    const jsFullPath = path.join(directory, "layout_data.js");

    writeFileSync(htmlFullPath, compiledLayout.layoutHTMLStart + compiledLayout.layoutHTMLEnd);
    writeFileSync(htmlMetadataFullPath, compiledLayout.layoutMetadataHTML);
    writeFileSync(jsFullPath, compiledLayout.specialElementOptions.join(","));
}

async function compileLayout(layoutInformation: LayoutInformation): Promise<CompiledLayout> {
    const compilationContext = generateLayoutCompilationContext(layoutInformation.pathname);

    const exports = layoutInformation.exports;
    const layoutConstructor = exports.layoutConstructor;
    const layoutMetadataConstructor = exports.layoutMetadataConstructor;

    /**
     * Use a marker element to denote the separation point of the start and end of the layout.
     */
    const layoutId = generateLayoutId(layoutInformation);
    const markerElement = `<template layout-id="${layoutId}"></template>`;

    let layoutRootElement: AnyElement;
    {
        if (isAsyncFunction(layoutConstructor)) {
            layoutRootElement = await layoutConstructor(markerElement);
        } else {
            layoutRootElement = (layoutConstructor(markerElement) as AnyElement);
        }
    }

    let layoutRootMetadataElement: AnyElement;
    {
        if (isAsyncFunction(layoutMetadataConstructor)) {
            layoutRootMetadataElement = await layoutMetadataConstructor();
        } else {
            layoutRootMetadataElement = (layoutMetadataConstructor() as AnyElement);
        }
    }

    let layoutSerializationResult: SerializationResult;
    let layoutMetadataSerializationResult: SerializationResult;

    try {
        layoutSerializationResult = serializeElement(compilationContext, layoutRootElement);
        layoutMetadataSerializationResult = serializeElement(compilationContext, layoutRootMetadataElement);
    } catch(e) {
        console.error(`Failed to serialize the elements of a layout with the pathname: "${layoutInformation.pathname}"`);
        throw e;
    }

    const layoutHTML = layoutSerializationResult.serializedElement;
    const layoutMetadataHTML = layoutMetadataSerializationResult.serializedElement;

    const layoutHTMLMarkerElementIndex = layoutHTML.indexOf(markerElement);

    // Ensure marker element is present.
    if (layoutHTMLMarkerElementIndex === -1) {
        throw invalidLayoutError(compilerOptions, layoutInformation.modulePath, "The marker element was not found in the compiled layout HTML. Make sure to use the \"child\" paramater passed into the layout function.");
    }

    /**
     * Split *after* the marker element, always leaving it at the layoutHTML start,
     * this let's us replace all the children *after* it, for client-side navigation.
     */
    const layoutHTMLStart = layoutHTML.slice(0, layoutHTMLMarkerElementIndex + markerElement.length);
    const layoutHTMLEnd = layoutHTML.slice(layoutHTMLMarkerElementIndex + markerElement.length);

    const specialElementOptions = [
        ...layoutSerializationResult.specialElementOptions, 
        ...layoutMetadataSerializationResult.specialElementOptions
    ];

    const compiledLayout = {
        layoutHTMLStart: layoutHTMLStart,
        layoutHTMLEnd: layoutHTMLEnd,
        layoutMetadataHTML: layoutMetadataHTML,
        specialElementOptions: specialElementOptions,
    };

    return compiledLayout;
}

/** 
 * Run the general compilation process for the project. 
 * This compiles all static-pages & static-layouts, as well as gathers a list of every page (dynamic and static) & layout (dynamic and static).
 * It also recursively copies your public directory into the distribution directory.
 */
async function compileEntireProject() {
    const allLayouts = await gatherAllLayouts();
    const allPages = await gatherAllPages(allLayouts);

    const compiledStaticPages = await compileStaticPages(allLayouts, allPages);

    console.log(compiledStaticPages)
}

/** 
 * Run the general compilation process for the project. 
 * This compiles all static-pages & static-layouts, as well as gathers a list of every page (dynamic and static) & layout (dynamic and static).
 * It then writes those values to compilerOptions -> outputDirectory/DIST
 * It also recursively copies your public directory into the distribution directory.
 */
async function compileEntireProjectToDisk() {
    throw new Error("Not yet implemented.");
}

export type {
    CompilerOptions
}

export {
    setCompilerOptions,
    generatePageCompilationContext,
    serializeElement,
    generatePageDataScript,
    compileEntireProject,

    compileEntireProjectToDisk,
    compilePageToDisk,
    compileLayoutToDisk,
}