/**
 * This file contains the functions used by compiler_process to compile pages.
 */


import path from "path";
import crypto from "crypto";
import { AnyElement, EleganceElement, SpecialElementOption } from "../elements/element";
import { cpSync, Dirent, existsSync, FSWatcher, lstatSync, mkdirSync, readdirSync, readFileSync, watch, writeFileSync } from "fs";
import esbuild from "esbuild";
import { invalidPageError, PageExports, PageInformation } from "../server/page";
import { invalidLayoutError, LayoutExports, LayoutInformation } from "../server/layout";
import { allElements } from "../elements/element_list";
import { observer, ObserverOption, ServerObserver } from "../client/observer";
import { fileURLToPath, pathToFileURL } from "url";
import util from "util";
import { AsyncLocalStorage } from "async_hooks";
import { ServerSubject } from "../client/state";
import { EventListenerOption, EventListener } from "../client/eventListener";
import { LoadHook } from "../client/loadHook";
import { formattedLog, formatToLog, LogLevel } from "../server/log";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// make sure to hook every element builder into the global scope
Object.assign(globalThis, allElements);

/** Context of a page that is currently being compiled. */
type PageCompilationContext = {
    /** The slash starting relative pathname (relative to pagesDirectory) of this page. */
    pathname: string,

    /** 
     * An id counter starting from 0, that is incremented once per generateID() call, 
     * and is used in conjunction with the pathname to generate unique static IDs (order-dependent) 
     */
    idCounter: number,
    usedHashes: string[],

    /**
     * Used by some tools to determine whether or not the current context is a page or a layout,
     * useful for stuff like loadHooks, which behave differently in layouts and pages.
     */
    kind: "page" | "layout",
};

/** Context of a layout that is currently being compiled. */
type LayoutCompilationContext = {
    /** The slash starting relative pathname (relative to pagesDirectory) of this layout. */
    pathname: string,

    /** 
     * An id counter starting from 0, that is incremented once per generateID() call, 
     * and is used in conjunction with the pathname to generate unique static IDs (order-dependent) 
     */
    idCounter: number,
    usedHashes: string[],

    /**
     * Used by some tools to determine whether or not the current context is a page or a layout,
     * useful for stuff like loadHooks, which behave differently in layouts and pages.
     */
    kind: "layout" | "page",
};

type CompilerOptions = {
    pagesDirectory: string;

    environment: "production" | "development",

    publicDirectory: string;

    outputDirectory: string;

    doHotReload: boolean;
};

type CompiledLayout = {
    /** Compiled result of the layoutConstructor */
    layoutHTMLStart: string,
    layoutHTMLEnd: string,

    /** Client data tokens generated by the layoutConstructor & layoutMetadataConstructor during it's compilation. */
    specialElementOptions: { elementKey: string, optionName: string, optionValue: SpecialElementOption }[],

    clientTokens: unknown[],

    /** Compiled result of the layoutMetadataConstructor */
    layoutMetadataHTML: string,
};

type CompiledPage = {
    pageHTML: string,
};

/** The result of turning an element into a string and extracting any special options from it. */
type SerializationResult = { 
    serializedElement: string, 
    specialElementOptions: { elementKey: string, optionName: string, optionValue: SpecialElementOption }[],
};

let compilerOptions: CompilerOptions;

/**
 * We use asynclocalstorage instead of globals to get rid of race conditions.
 * We run the code inside asynclocalstorage, and then all of the values get dumped into here instead of globalThis.
 * A much cleaner approach than previous.
 */
type CompilerStore = {
    generateId: () => string,

    addClientToken: (value: unknown) => void,

    compilationContext: PageCompilationContext | LayoutCompilationContext,
};

const compilerStore = new AsyncLocalStorage<CompilerStore>();

/**
 * Get the current dist dir. If it does not exist, it will be created.
 */
function getDistDir() {
    const fullPath = path.join(compilerOptions.outputDirectory, "DIST");

    if (existsSync(fullPath) === false) {
        mkdirSync(fullPath, { recursive: true, })
    }

    return fullPath;
}

function setCompilerOptions(newOptions: CompilerOptions) {
    newOptions.pagesDirectory = path.resolve(newOptions.pagesDirectory);
    newOptions.outputDirectory = path.resolve(newOptions.outputDirectory);
    newOptions.publicDirectory = path.resolve(newOptions.publicDirectory);

    if (existsSync(newOptions.pagesDirectory) === false) {
        throw new Error(newOptions.pagesDirectory + " does not exist, and thus cannot be used as the pagesDirectory.");
    }

    if (existsSync(newOptions.publicDirectory) === false) {
        throw new Error(newOptions.publicDirectory + " does not exist, and thus cannot be used as the publicDirectory");
    }

    if (existsSync(newOptions.outputDirectory) === false) {
        mkdirSync(newOptions.outputDirectory, { recursive: true, })
    }

    compilerOptions = newOptions;
}


function invalidElementError(element: AnyElement, fullPath: string[], reason: string): string {
    const stacktrace = formatStacktrace(fullPath);

    return ("Direct Parent Trace:\n" + stacktrace + "\n" + "The element \"" + util.inspect(element, { depth: 1, colors: true, }) + "\" is an invalid element. Reason:\n" + reason);
}

/** 
 * Generate a stable, page-specific & order-dependent unique-identifier. 
 * NOTE: This function will throw if it fails to generate a hash after 100+ attempts.
 * However, this is not technically possible.
 */
function generateId(compilationContext: PageCompilationContext): string {
    let id: string;
    let tries = 0;

    while (true) {
        compilationContext.idCounter += 1;

        id = crypto
            .createHash('sha256')
            .update(compilationContext.pathname + ':' + compilationContext.idCounter.toString())
            .digest('base64url')
            .slice(0, 11); // 66 bits of entropy

        if (!compilationContext.usedHashes.includes(id)) {
            break;
        }

        tries += 1;

        if (tries > 100) {
            throw new Error("Failed to generate a unique id after 100+ attempts");
        }
    }
    
    compilationContext.usedHashes.push(id);

    return id;
}

function generateLayoutId(layoutInformation: LayoutInformation): string {
    return crypto
        .createHash('sha256')
        .update(layoutInformation.pathname)
        .digest('base64url')
        .slice(0, 11); // 66 bits of entropy
}

function internalCompilerError(reason: string) {
    return new Error(`The compiler has encountered an internal error.\n${reason}`);
}

/** Take any directory pathname, and make it into this format: /path */
function sanitizePathname(pathname: string = ""): string {
    if (!pathname) return "/";

    pathname = "/" + pathname;

    pathname = pathname.replace(/\/+/g, "/");

    if (pathname.length > 1 && pathname.endsWith("/")) {
        pathname = pathname.slice(0, -1);
    }

    return pathname;
}

function getElementKey(compilationContext: PageCompilationContext, element: EleganceElement<any>): string {
    if (element.key) return element.key;

    element.key = generateId(compilationContext);

    return element.key;
}

function generatePageCompilationContext(pathname: string): PageCompilationContext {
    pathname = sanitizePathname(pathname);

    const absPath = path.join(getDistDir(), pathname);
    if (!existsSync(absPath)) mkdirSync(absPath, { recursive: true });

    return {
        pathname: pathname,
        idCounter: 0,
        usedHashes: [],
        kind: "page",
    };
}

function generateLayoutCompilationContext(pathname: string): LayoutCompilationContext {
    pathname = sanitizePathname(pathname);

    const absPath = path.join(getDistDir(), pathname);
    if (!existsSync(absPath)) mkdirSync(absPath, { recursive: true });

    return {
        pathname: pathname,
        idCounter: 0,
        usedHashes: [],
        kind: "layout",
    };
}

const builtPackages = new Map<string, true>();
/**
 * Make a set list of package available in the browser.
 * Each package will be bundled individually, and placed in publicDirectory/DIST/__packages/, under their respective globalname + ".js".
 * 
 * 
 * Note that this will bundle the *entire* library, which can be quite large.
 * 
 * Check if the library you're shipping has a browser-friendly version for use.
 * Each package is only ever built once, but every file that wants to use the package must re-call clientPackages(), to ensure the appropriate script-tag is added to the page's HTML. 
 * 
 * If a layout calls clientPackages, thus generating the <script> tag, you should not call it in the page, since it's unnecessary.
 * 
 * **NOTE:** This currently only works with JS files and node_modules packages. ESBuild cannot resolve local typescript files.
 * @param packages Key-value pair of globalName and packagePath.
 */
class ShippedPackage {
    globalName: string;
    packagePath: string;

    constructor(globalName: string, packagePath: string) {
        this.globalName = globalName;
        this.packagePath = packagePath;
    }

    serialize(): string {
        return `<script data-package="true" src="/__packages/${this.globalName}.js" defer="true"></script>`;
    }
}

function clientPackages(packages: { [globalName: string]: string, }) {
    for (const [globalName, packagePath] of Object.entries(packages)) {
        const store = compilerStore.getStore();

        if (!store) {
            throw formattedLog(LogLevel.ERROR, "Invalid invocation of clientPackages(). Ensure this function is never called outside of a page or layout constructor.")
        }

        const shippedPackage = new ShippedPackage(globalName, packagePath);

        store?.addClientToken(shippedPackage);

        if (builtPackages.has(globalName+packagePath)) {
            continue;
        }

        const fullPath = packagePath;

        esbuild.build({
            entryPoints: [fullPath],
            bundle: true,
            outfile: path.join(getDistDir(), "__packages", globalName + ".js"),
            format: "iife",
            platform: "browser",
            globalName: globalName,
            loader: {
                ".ts": "ts",
                ".js": "js",
                ".cjs": "js",
                ".mjs": "js",
            },
            minify: true,
            treeShaking: true,
        }).catch((error) => {
            formattedLog(LogLevel.ERROR, "Failed to ship package \"", globalName, "\".")
            console.error(error);
        });
    }
}

function serializeEleganceElement(
    compilationContext: PageCompilationContext,
    element: EleganceElement<any>,
    path: string[] = [],
): SerializationResult {

    let serializedElement = "";
    let specialElementOptions: { elementKey: string, optionName: string, optionValue: SpecialElementOption }[] = [];

    serializedElement += `<${element.tag}`;
    
    // Process options.
    {
        const entries = Object.entries(element.options);

        for (const [optionName, optionValue] of entries) {
            if (optionValue instanceof SpecialElementOption) {
                optionValue.mutate(element, optionName);

                const elementKey = getElementKey(compilationContext, element);

                specialElementOptions.push({ elementKey, optionName, optionValue });
            } else {
                serializedElement += ` ${optionName}="${optionValue}"`;
            }
        }
    }

    if (element.key) {
        serializedElement += ` key="${element.key}"`;
    }

    serializedElement += ">";
    
    // Process children.
    {
        if (element.children === null) {
            return { serializedElement, specialElementOptions };
        }

        if (element.children.length > 0) {
            for (const child of element.children) {
                const result = serializeElement(compilationContext, child, path)

                serializedElement += result.serializedElement;
                specialElementOptions.push(...result.specialElementOptions);
            }
        }
    }

    serializedElement += `</${element.tag}>`;

    return { serializedElement, specialElementOptions  };
}

/**
 * Take any element, and turn it into a valid HTML string.
 * Throw an error whenever an element is considered invalid.
 * @param compilationContext The context of the page or layout that we're compiling
 * @param element The element to serialize.
 * @returns The serialized element, and any special options that were encountered.
 */
function serializeElement(
    compilationContext: PageCompilationContext,
    element: AnyElement,
    path: string[] = [],
): SerializationResult {
    const currentRepr = getElementRepr(element);
    const fullPath = [...path, currentRepr];

    let serializedElement: string;
    let specialElementOptions: { elementKey: string, optionName: string, optionValue: SpecialElementOption }[] = [];

    if (element === undefined || element === null) {
        throw invalidElementError(element, fullPath, `Undefined and null are not allowed as elements.`);
    }

    switch (typeof element) {
    case "object":
        if (Array.isArray(element)) {
            let serializedElements = "";

            for (const [index, subElement] of element.entries()) {
                const childPath = [...path, `${currentRepr} at index ${index}`];
                const serializationResult = serializeElement(compilationContext, subElement, childPath);

                serializedElements += serializationResult.serializedElement;
                specialElementOptions.push(...serializationResult.specialElementOptions);
            }

            serializedElement = serializedElements;

            break;
        }

        if (element instanceof EleganceElement) {
            const result = serializeEleganceElement(compilationContext, element, fullPath);

            serializedElement = result.serializedElement;
            specialElementOptions.push(...result.specialElementOptions);

            break;
        }

        throw invalidElementError(element, fullPath, `This element is an arbitrary object, and arbitrary objects are not valid children. Please make sure all elements are one of: EleganceElement, boolean, number, string or Array.`);
    case "boolean":
        serializedElement = `${element}`;
        break;
    case "number":
        serializedElement = element.toString();
        break;
    case "string":
        serializedElement = element;
        break;
    default:
        throw invalidElementError(element, fullPath, `The typeof of this element is not one of EleganceElement, boolean, number, string or Array. Please convert it into one of these types.`);
    }

    return { serializedElement, specialElementOptions };
}

function prettyObj(obj: any, level: number = 0): string {
    const ind = '  '.repeat(level);
    const entries = Object.entries(obj);
    
    if (entries.length === 0) return '{}';

    let str = '{\n';

    for (const [key, value] of entries) {
        let valRepr: string;

        if (typeof value === 'object' && value !== null) {
            valRepr = prettyObj(value, level + 1);
        } else {
            valRepr = JSON.stringify(value);
        }

        str += `${ind}  ${key}: ${valRepr},\n`;
    }

    str = str.slice(0, -2); // remove trailing commad
    str += `\n${ind}}`;

    return str;
}

function getElementRepr(element: AnyElement): string {
    if (element === null) return 'null';
    if (element === undefined) return 'undefined';

    if (typeof element === 'string') return `"${element.replace(/"/g, '\\"')}"`;
    if (typeof element === 'number') return element.toString();
    if (typeof element === 'boolean') return element.toString();
    
    if (Array.isArray(element)) {
        return `Array(length: ${element.length})`;
    }

    if (element instanceof EleganceElement) {
        const tag = (element as any).tag || 'unknown';
        const options = (element as any).options || {};

        if (Object.keys(options).length === 0) {
            return `${tag}({})`;
        }

        return `${tag}(${prettyObj(options)})`;
    }

    return `Unknown(${typeof element})`;
}

function formatStacktrace(path: string[]): string {
    let lastReprColumn = 0;
    const result: string[] = [];

    path.forEach((repr, index) => {
        const isLast = index === path.length - 1;
        const lines = repr.split('\n');

        let prefix = '';

        if (index > 0) {
            prefix = ' '.repeat(lastReprColumn + 1) + '∟> ';
        }

        let firstLine = prefix + lines[0];

        if (isLast) {
            firstLine = prefix + `\x1b[41;30m${lines[0]}`;
        }

        result.push(firstLine);

        const reprColumn = lines[0].search(/\S|$/);
        lastReprColumn = prefix.length + reprColumn;

        for (let i = 1; i < lines.length; i++) {
            const subLine = ' '.repeat(prefix.length) + lines[i];
            
            result.push(subLine);
        }

        if (isLast) {
            result[result.length - 1] += `\x1b[0m`;
        }
    });

    return result.join('\n');
}

/**
 * This function uses string interpolation to transform client tokens and special element options into a script tag that is then sent to the client.
 * The client tokens are not *fully* serialized, but the necessary components to re-create them as client versions of the corresponding thing *are* serialized.
 * For example, the serialize() method of EventListener is not sent, but it's callback, id, and dependencies (as ids) are.
 * String interpolation is dangerous and error-prone, so if you're going to add something to this function, ensure you know what you're doing,
 * and make sure to also edit runtime.ts to handle the clientTokens that you send to the browser. I did not create separate datatypes in the runtime for the intermediary forms of things like EventListeners, 
 * LoadHooks, etc, for I did not feel it necessary, but do not that these types do not exactly line up 100%.
 * @param compilationContext The current context of what we're compiling, can be either layout or page compilation context.
 * @param specialElementOptions An array of special element options that were found during serialization of the elements of whatever we're currently compiling
 * @param clientTokens An array of tokens that will be serialized and shipped within the pageDataScript.
 * @returns A string containing the page data <script> tag.
 */
async function generatePageDataScript(
    compilationContext: PageCompilationContext, 
    specialElementOptions: { elementKey: string, optionName: string, optionValue: SpecialElementOption }[],
    clientTokens: unknown[],
) {
    let dataScriptContent = `export const data = {`;

    const serverSubjects = clientTokens.filter(t => t instanceof ServerSubject);
    const loadHooks = clientTokens.filter(t => t instanceof LoadHook);
    const eventListeners = clientTokens.filter(t => t instanceof EventListener);
    const serverObservers = clientTokens.filter(t => t instanceof ServerObserver);

    {
        dataScriptContent += "subjects:[";

        for (const serverSubject of serverSubjects) {
            let value = serverSubject.value.toString();
            if (typeof value === "string") {
                value = `"${value}"`
            }
            const id = serverSubject.id;

            dataScriptContent += `{id:"${id}",value:${value}},`;
        }

        dataScriptContent += "],";
    }

    {
        dataScriptContent += "loadHooks:[";
        for (const loadHook of loadHooks) {
            dataScriptContent += loadHook.serialize();
            dataScriptContent += ",";
        }
        dataScriptContent += "],";
    }

        {
        dataScriptContent += "eventListeners:[";
        for (const eventListener of eventListeners) {
            dataScriptContent += eventListener.serialize();
            dataScriptContent += ",";
        }
        dataScriptContent += "],";
    }
    
    {
        dataScriptContent += "observers:[";
        for (const serverObserver of serverObservers) {
            dataScriptContent += serverObserver.serialize();
            dataScriptContent += ",";
        }
        dataScriptContent += "],";
    }

    {
        const eventListenerOptions = specialElementOptions.filter(seo => seo.optionValue instanceof EventListenerOption);

        dataScriptContent += "eventListenerOptions:[";
        for (const eventListenerOption of eventListenerOptions) {
            const eventListener = eventListenerOption.optionValue;
            const optionName = eventListenerOption.optionName;
            const elementKey = eventListenerOption.elementKey;

            const result = eventListener.serialize(optionName, elementKey);
            dataScriptContent += `${result},`;
        }
        dataScriptContent += "],";
    }

    {
        const observerOptions = specialElementOptions.filter(seo => seo.optionValue instanceof ObserverOption);

        dataScriptContent += "observerOptions:[";
        for (const observerOption of observerOptions) {
            const observer = observerOption.optionValue;
            const optionName = observerOption.optionName;
            const elementKey = observerOption.elementKey;

            const result = observer.serialize(optionName, elementKey);
            dataScriptContent += `${result},`;
        }
        dataScriptContent += "]";
    }

    dataScriptContent += "};\n";

    const transformedResult = await esbuild.transform(dataScriptContent, { minify: true, });
    dataScriptContent = transformedResult.code;

    let dataScript = `<script data-hook="true" data-pathname="${compilationContext.pathname}" type="text/plain">${dataScriptContent}</script>`;
    let dataLoaderScript = `<script>
            const dataScript = document.querySelector('[data-hook="true"][data-pathname="${compilationContext.pathname}"][type="text/plain"');
            const text = dataScript.textContent;
            dataScript.remove();
            const blob = new Blob([text], { type: 'text/javascript' });
            const url = URL.createObjectURL(blob);
            
            const script = document.createElement("script");
            script.src = url;
            script.type = "module";
            script.setAttribute("data-page", "true");
            script.setAttribute("data-pathname", "${compilationContext.pathname}");
            
            document.head.appendChild(script);
            
            document.currentScript.remove();
        </script>`.replace(" ", "").replace("\n", "");

    const shippedPackages = clientTokens.filter(t => t instanceof ShippedPackage);
    let packagesString = "";
    for (const shippedPackage of shippedPackages) {
        packagesString += shippedPackage.serialize();
    }

    return dataScript + dataLoaderScript + packagesString;
}

/** 
 * Go through a directory, including all it's subdirectories, 
 * and call callback() for each file.
 */
async function walkDirectory(fullPath: string, callback: (file: Dirent) => Promise<void>) {
    const stack: Dirent[] = [];

    stack.push(...readdirSync(fullPath, { withFileTypes: true, }));

    while (true) {
        const entry = stack.pop();
        if (!entry) break;

        if (entry.isDirectory()) {
            const fullPath = path.join(entry.parentPath, entry.name);

            stack.push(...readdirSync(fullPath, { withFileTypes: true, }));

            continue;
        }

        if (!entry.isFile()) continue;

        await callback(entry);
    }
}

/** 
 * Get a structured, validated and formatted version of the exports of a page.ts file
 * This file *should* be the first thing that imports a page.
 */
async function getPageExports(modulePath: string): Promise<PageExports> {
    const rawExports = await import("file://" + modulePath).catch((err: unknown) => {
        console.error(`Encountered an error in file:\n    ${modulePath}`);
        throw err;
    });

    let isDynamic = rawExports?.isDynamic === true

    const pageConstructor = rawExports.page;
    {
        if (typeof pageConstructor !== "function") {
            throw invalidPageError(compilerOptions, modulePath, "The type of the export \"page\" is not a function, and is instead of type: " + typeof pageConstructor);
        }
    }

    const pageMetadataConstructor = rawExports.metadata;
    {
        if (typeof pageMetadataConstructor !== "function") {
            throw invalidPageError(compilerOptions, modulePath, "The type of the export \"metadata\" is not a function, and is instead of type: " + typeof pageMetadataConstructor);
        }
    }
    
    return {
        isDynamic,
        pageConstructor,
        pageMetadataConstructor,
    };
}

/** 
 * Get a structured, validated and formatted version of the exports of a layout.ts file
 * This file *should* be the first thing that imports a page.
 */
async function getLayoutExports(modulePath: string): Promise<LayoutExports> {
    const rawExports = await import("file://" + modulePath);

    let isDynamic = rawExports?.isDynamic === true

    const layoutConstructor = rawExports.layout;
    {
        if (typeof layoutConstructor !== "function") {
            throw invalidLayoutError(compilerOptions, modulePath, "The type of the export \"layout\" is not a function, and is instead of type: " + typeof layoutConstructor);
        }
    }

    const layoutMetadataConstructor = rawExports.metadata;
    {
        if (typeof layoutMetadataConstructor !== "function") {
            throw invalidLayoutError(compilerOptions, modulePath, "The type of the export \"metadata\" is not a function, and is instead of type: " + typeof layoutMetadataConstructor);
        }
    }
    
    return {
        isDynamic,
        layoutConstructor,
        layoutMetadataConstructor,
    };
}

async function getApplicablePageLayouts(allLayouts: Map<string, LayoutInformation>, pagePathname: string): Promise<LayoutInformation[]> {
    const pageLayouts: LayoutInformation[] = [];

    for (const [_, layoutInformation] of allLayouts.entries()) {
        const doesLayoutApply = pagePathname.startsWith(layoutInformation.pathname);

        if (!doesLayoutApply) continue;

        pageLayouts.push(layoutInformation);
    }

    pageLayouts.sort((a: LayoutInformation, b: LayoutInformation) => a.pathname.length - b.pathname.length);

    return pageLayouts;
}

async function gatherAllPages(allLayouts: Map<string, LayoutInformation>): Promise<Map<string, PageInformation>> {
    const pageMap = new Map();

    await walkDirectory(compilerOptions.pagesDirectory, async (file) => {
        if (file.name !== "page.ts") return;

        const fullPath = path.join(file.parentPath, file.name);
        const pathname = sanitizePathname(path.relative(compilerOptions.pagesDirectory, file.parentPath));

        const exports = await getPageExports(fullPath);
        const applicablePageLayouts = await getApplicablePageLayouts(allLayouts, pathname);

        const pageInformation: PageInformation = {
            modulePath: fullPath,
            exports: exports,
            pathname: pathname,
            applicableLayouts: applicablePageLayouts,
        };

        pageMap.set(pathname, pageInformation);
    })

    return pageMap;
}

async function gatherAllLayouts(): Promise<Map<string, LayoutInformation>> {
    const layoutMap = new Map();

    await walkDirectory(compilerOptions.pagesDirectory, async (file) => {
        if (file.name !== "layout.ts") return;

        const fullPath = path.join(file.parentPath, file.name);
        const pathname = sanitizePathname(path.relative(compilerOptions.pagesDirectory, file.parentPath));

        const exports = await getLayoutExports(fullPath);

        const layoutInformation: LayoutInformation = {
            modulePath: fullPath,
            exports: exports,
            pathname: pathname,
        };

        layoutMap.set(pathname, layoutInformation);
    })

    return layoutMap;
}

const compiledStaticLayouts = new Map<string, CompiledLayout>();
async function getCompiledLayout(layoutInformation: LayoutInformation, allLayouts: Map<string, LayoutInformation>): Promise<CompiledLayout> {
    if (layoutInformation.exports.isDynamic === true) {
        return await compileLayout(layoutInformation);
    }

    if (compiledStaticLayouts.has(layoutInformation.pathname)) {
        return compiledStaticLayouts.get(layoutInformation.pathname)!;
    }

    const compiledLayout = await compileLayout(layoutInformation);
    compiledStaticLayouts.set(layoutInformation.pathname, compiledLayout);

    return compiledLayout;
}

async function compilePageToDisk(
    allLayouts: Map<string, LayoutInformation>, 
    pageInformation: PageInformation
): Promise<CompiledPage> {
    const compiledPage = await compilePage(allLayouts, pageInformation);

    const targetPath = path.join(
        getDistDir(),
        pageInformation.pathname,
        "index.html",
    );

    writeFileSync(targetPath, compiledPage.pageHTML)

    return compiledPage;
}

/** Returns the standard children of <head> that must exist on every page independent of it's content. */
function getEnforcedMetadata(): string {
    return `<meta charset="utf-8"><script defer="true" src="/client.js"></script>`;
}
async function compilePage(
    allLayouts: Map<string, LayoutInformation>, 
    pageInformation: PageInformation
): Promise<CompiledPage> {
    const compilationContext = generatePageCompilationContext(pageInformation.pathname);

    const exports = pageInformation.exports;
    const pageConstructor = exports.pageConstructor;
    const pageMetadataConstructor = exports.pageMetadataConstructor;

    /**
     * Populate compilerStore.
     * Usage of AsyncLocalStorage allows us to have "globals" without globals,
     * as each call to run has it's own "context", removing concurrency issues.
     */
    const clientTokens: unknown[] = [];

    const storeTools: CompilerStore = {
        generateId: () => generateId(compilationContext),

        addClientToken: (value: unknown) => {
            clientTokens.push(value);
        },

        compilationContext,
    };

    let pageRootElement = await compilerStore.run(storeTools, async () => {
        return await pageConstructor();
    })

    let pageRootMetadataElement = await compilerStore.run(storeTools, async () => {
        return await pageMetadataConstructor();
    })

    let pageSerializationResult: SerializationResult;
    let pageMetadataSerializationResult: SerializationResult;
    try {
        pageSerializationResult = serializeElement(compilationContext, pageRootElement);
        pageMetadataSerializationResult = serializeElement(compilationContext, pageRootMetadataElement);
    } catch(e) {
        formattedLog(LogLevel.ERROR, `${pageInformation.pathname}/page.ts - Element serialization failed.`);
        throw e;
    }

    const allClientTokens = [ ...clientTokens, ];

    const allSpecialElementOptions = [
        ...pageSerializationResult.specialElementOptions, 
        ...pageMetadataSerializationResult.specialElementOptions,
    ];

    const pageHTML = pageSerializationResult.serializedElement;
    const pageMetadataHTML = pageMetadataSerializationResult.serializedElement;

    let finalHTML: string = "<!DOCTYPE html>";

    // go through the layouts, and construct the end-stage page html
    if (pageInformation.applicableLayouts.length > 0) {
        const rootLayout = pageInformation.applicableLayouts[0];
        const compiledRootLayout = await getCompiledLayout(rootLayout, allLayouts);

        const htmlTagIndex = compiledRootLayout.layoutHTMLStart.indexOf("<html");
        const htmlTagEndIndex = compiledRootLayout.layoutHTMLStart.indexOf(">");

        if (htmlTagIndex === -1 || htmlTagEndIndex === -1) {
            throw invalidLayoutError(compilerOptions, rootLayout.modulePath, "The root layout must start with an html() element.");
        }

        if (compiledRootLayout.layoutHTMLStart.includes("<body") === false) {
            throw invalidLayoutError(compilerOptions, rootLayout.modulePath, "The root layout must contain the body() element.");
        }

        const beforeHead = compiledRootLayout.layoutHTMLStart.substring(0, htmlTagEndIndex + 1);
        const afterHead = compiledRootLayout.layoutHTMLStart.substring(htmlTagEndIndex + 1);

        // gather the content of the head element, and inject it right after the <html> opening tag
        let headContent = "";
        {
            headContent += "<head>";
                headContent += getEnforcedMetadata();

                for (const layoutInformation of pageInformation.applicableLayouts) {
                    const compiledLayout = await getCompiledLayout(layoutInformation, allLayouts);

                    headContent += compiledLayout.layoutMetadataHTML;

                    allSpecialElementOptions.push(...compiledLayout.specialElementOptions);
                    allClientTokens.push(...compiledLayout.clientTokens);
                }
                
                headContent += pageMetadataHTML

            headContent += "</head>";
        }

        finalHTML += beforeHead + headContent + afterHead;

        // skip the root layout, since we already added it in.
        for (let i = 1; i < pageInformation.applicableLayouts.length; i++) {
            const layoutInformation = pageInformation.applicableLayouts[i];

            const compiledLayout = await getCompiledLayout(layoutInformation, allLayouts);

            finalHTML += compiledLayout.layoutHTMLStart;
        }

        finalHTML += pageHTML

        let endString = "";

        for (const layoutInformation of [...pageInformation.applicableLayouts].reverse()) {
            const compiledLayout = await getCompiledLayout(layoutInformation, allLayouts);

            endString += compiledLayout.layoutHTMLEnd;
        }

        const htmlEndTagIndex = endString.indexOf("</body>");
        if (htmlEndTagIndex === -1) {
            throw internalCompilerError("Failed to find </body> tag whilst compiling a page");
        }

        const beforeEndTag = endString.substring(0, htmlEndTagIndex);
        const afterEndTag = endString.substring(htmlEndTagIndex);

        const pageDataScript = await generatePageDataScript(compilationContext, allSpecialElementOptions, clientTokens);

        finalHTML += beforeEndTag + pageDataScript + afterEndTag;
    } else {
        finalHTML += `<html lang="en-us">`;
            finalHTML += "<head>";
                finalHTML += getEnforcedMetadata();
                finalHTML += pageMetadataHTML;
            finalHTML += "</head>";
            
            finalHTML += "<body>";
                finalHTML += pageHTML;

                const pageDataScript = await generatePageDataScript(compilationContext, allSpecialElementOptions, clientTokens);

                finalHTML += pageDataScript;
            finalHTML += "</body>";
        finalHTML += `</html>`;
    }

    const compiledPage = {
        pageHTML: finalHTML,
    };

    return compiledPage;
}

async function compileStaticPages(
    allLayouts: Map<string, LayoutInformation>, 
    allPages: Map<string, PageInformation>
): Promise<Map<string, CompiledPage>> {
    const compiledPages = new Map();

    for (const [pagePathname, pageInformation] of allPages) {
        if (pageInformation.exports.isDynamic === true) continue;

        const compiledPage = await compilePage(allLayouts, pageInformation);
        
        compiledPages.set(pagePathname, compiledPage);
    }

    return compiledPages;
}

async function compileStaticPagesToDisk(
    allLayouts: Map<string, LayoutInformation>, 
    allPages: Map<string, PageInformation>
): Promise<Map<string, CompiledPage>> {
    const compiledPages = new Map();

    for (const [pagePathname, pageInformation] of allPages) {
        if (pageInformation.exports.isDynamic === true) continue;

        const compiledPage = await compilePageToDisk(allLayouts, pageInformation);
        
        compiledPages.set(pagePathname, compiledPage);
    }

    return compiledPages;
}

async function compileLayoutToDisk(layoutInformation: LayoutInformation): Promise<void> {
    const compiledLayout = await compileLayout(layoutInformation);

    const directory = path.join(getDistDir(), layoutInformation.pathname);
    const htmlFullPath = path.join(directory, "layout.html");
    const htmlMetadataFullPath = path.join(directory, "layout_metadata.html");
    const jsFullPath = path.join(directory, "layout_data.js");

    writeFileSync(htmlFullPath, compiledLayout.layoutHTMLStart + compiledLayout.layoutHTMLEnd);
    writeFileSync(htmlMetadataFullPath, compiledLayout.layoutMetadataHTML);
    writeFileSync(jsFullPath, compiledLayout.specialElementOptions.join(","));
}

async function compileLayout(layoutInformation: LayoutInformation): Promise<CompiledLayout> {
    const compilationContext = generateLayoutCompilationContext(layoutInformation.pathname);

    const exports = layoutInformation.exports;
    const layoutConstructor = exports.layoutConstructor;
    const layoutMetadataConstructor = exports.layoutMetadataConstructor;

    /**
     * Use a marker element to denote the separation point of the start and end of the layout.
     */
    const layoutId = generateLayoutId(layoutInformation);
    const markerElement = `<template layout-id="${layoutId}"></template>`;

    /**
     * Populate compilerStore.
     * Usage of AsyncLocalStorage allows us to have "globals" without globals,
     * as each call to run has it's own "context", removing concurrency issues.
     */
    const clientTokens: unknown[] = [];

    const storeTools: CompilerStore = {
        generateId: () => generateId(compilationContext),
        addClientToken: (value) => {
            clientTokens.push(value);
        },

        compilationContext,
    };

    let layoutRootElement: AnyElement = await compilerStore.run(storeTools, async () => await layoutConstructor(markerElement));

    let layoutRootMetadataElement: AnyElement = await compilerStore.run(storeTools, async () => await layoutMetadataConstructor());

    let layoutSerializationResult: SerializationResult;
    let layoutMetadataSerializationResult: SerializationResult;

    try {
        layoutSerializationResult = serializeElement(compilationContext, layoutRootElement);
        layoutMetadataSerializationResult = serializeElement(compilationContext, layoutRootMetadataElement);
    } catch(e) {
        console.error(`${layoutInformation.pathname}/layout.ts - Failed to serialize elements.`);
        throw e;
    }

    const layoutHTML = layoutSerializationResult.serializedElement;
    const layoutMetadataHTML = layoutMetadataSerializationResult.serializedElement;

    const layoutHTMLMarkerElementIndex = layoutHTML.indexOf(markerElement);

    // Ensure marker element is present.
    if (layoutHTMLMarkerElementIndex === -1) {
        throw invalidLayoutError(compilerOptions, layoutInformation.modulePath, "The marker element was not found in the compiled layout HTML. Make sure to use the \"child\" paramater passed into the layout function.");
    }

    /**
     * Split *after* the marker element, always leaving it at the layoutHTML start,
     * this let's us replace all the children *after* it, for client-side navigation.
     */
    const layoutHTMLStart = layoutHTML.slice(0, layoutHTMLMarkerElementIndex + markerElement.length);
    const layoutHTMLEnd = layoutHTML.slice(layoutHTMLMarkerElementIndex + markerElement.length);

    const specialElementOptions = [
        ...layoutSerializationResult.specialElementOptions, 
        ...layoutMetadataSerializationResult.specialElementOptions
    ];

    const compiledLayout = {
        layoutHTMLStart: layoutHTMLStart,
        layoutHTMLEnd: layoutHTMLEnd,
        layoutMetadataHTML: layoutMetadataHTML,
        specialElementOptions: specialElementOptions,
        clientTokens: clientTokens,
    };

    return compiledLayout;
}

/**
 * Transpile the client runtime from typescript into javascript and place it into the dist directory
 */
async function transpileClientRuntime() {
    const clientTsPath = path.join(__dirname, "..", "client", "runtime.ts");

    if (!existsSync(clientTsPath)) {
        throw internalCompilerError("Failed to find the client runtime at path:" + clientTsPath);
    }

    const targetPath = path.join(
        getDistDir(),
        "client.js",
    );

    await esbuild.build({
        bundle: true,
        entryPoints: [clientTsPath],
        outfile: targetPath,
        format: "iife",
        platform: "browser",
        minify: true,
        external: ["util"],
        treeShaking: true,
        loader: {
            ".ts": "ts",
        },
        dropLabels: [
            compilerOptions.environment === "production" ? "DEV_BUILD" : "PROD_BUILD"
        ],
        define: compilerOptions.environment === "production" ? {
            "DEV_BUILD": "false",
            "PROD_BUILD": "true",
        } : {
            "PROD_BUILD": "false",
            "DEV_BUILD": "true",
        },
    });
}

function createRecursiveWatcher(
    targetDir: string,
    callback: (path: string) => Promise<void>
): void {
    const watchers = new Map<string, FSWatcher>();
    const timeouts = new Map<string, NodeJS.Timeout>();

    function debouncedCallback(fullPath: string): void {
        const existingTimeout = timeouts.get(fullPath);
        if (existingTimeout) {
            clearTimeout(existingTimeout);
        }

        const timeout = setTimeout(async function() {
            try {
                await callback(fullPath);
            } catch (err) {
                console.error(err);
            } finally {
                timeouts.delete(fullPath);
            }
        }, 100);

        timeouts.set(fullPath, timeout);
    }

    function unregisterWatcher(path: string): void {
        for (const [dir, watcher] of watchers.entries()) {
            if (dir === path || dir.startsWith(path + '/')) {
                watcher.close();
                watchers.delete(dir);
                
                const timeout = timeouts.get(dir);
                if (timeout) {
                    clearTimeout(timeout);
                    timeouts.delete(dir);
                }
            }
        }
    }

    function registerWatcher(dirPath: string): void {
        if (watchers.has(dirPath)) return;

        try {
            const watcher = watch(dirPath, { recursive: false }, function(event, filename) {
                if (!filename) return;

                const fullPath = path.join(dirPath, filename);

                try {
                    const stats = lstatSync(fullPath);
                    if (stats.isDirectory()) {
                        registerWatcher(fullPath);
                    }
                    debouncedCallback(fullPath);
                } catch (err: any) {
                    if (err.code === 'ENOENT') {
                        unregisterWatcher(fullPath);
                        debouncedCallback(fullPath);
                    }
                }
            });

            watcher.on('error', function() {
                unregisterWatcher(dirPath);
            });

            watchers.set(dirPath, watcher);

            const files = readdirSync(dirPath);
            for (const file of files) {
                const childPath = path.join(dirPath, file);
                try {
                    if (lstatSync(childPath).isDirectory()) {
                        registerWatcher(childPath);
                    }
                } catch (e) {}
            }
        } catch (e) {}
    }

    registerWatcher(targetDir);
}

/** 
 * Run the general compilation process for the project. 
 * This compiles all static-pages & static-layouts, as well as gathers a list of every page (dynamic and static) & layout (dynamic and static).
 * It also recursively copies your public directory into the distribution directory.
 * If doHotReload is true, it will also enable hot-reloading.
 */
async function compileEntireProject() {
    const gracefulErr = (err: unknown) => { console.error(err); }

    process.on("uncaughtException", gracefulErr);
    process.on("unhandledRejection", gracefulErr);

    if (compilerOptions.doHotReload) {
        createRecursiveWatcher(compilerOptions.pagesDirectory, async (path) => {
            process.send?.(`restart-me`);
        })

        process.send?.("enable-hot-reload")
    }

    const allLayouts = await gatherAllLayouts();
    const allPages = await gatherAllPages(allLayouts);
    const allStatusCodePages = new Map<string, PageInformation>();

    const compiledStaticPages = await compileStaticPagesToDisk(allLayouts, allPages);

    await transpileClientRuntime();

    cpSync(compilerOptions.publicDirectory, getDistDir(), { recursive: true, });

    process.off("uncaughtException", gracefulErr);
    process.off("unhandledRejection", gracefulErr);

    return {
        allPages,
        allLayouts,
        allStatusCodePages,
        compiledStaticPages,
        compiledStaticLayouts,
    }
}


/** 
 * Run the general compilation process for the project. 
 * This compiles all static-pages & static-layouts, as well as gathers a list of every page (dynamic and static) & layout (dynamic and static).
 * It then writes those values to compilerOptions -> outputDirectory/DIST
 * It also recursively copies your public directory into the distribution directory.
 */
async function compileEntireProjectToDisk() {
    throw new Error("Not yet implemented.");
}

export type {
    CompilerOptions,
    CompiledLayout,
    CompiledPage,
}

export {
    setCompilerOptions,
    generatePageCompilationContext,
    generateLayoutCompilationContext,
    serializeElement,
    generatePageDataScript,
    compileEntireProject,

    compileEntireProjectToDisk,
    compilePageToDisk,
    compileLayoutToDisk,

    compilerStore,

    compilerOptions,

    compilePage,
    compileLayout,

    clientPackages,
}