export const ALL_TAGS = [
    "html", "head", "title", "base", "link", "meta", "style", "body",
    "article", "section", "nav", "aside", "h1", "h2", "h3", "h4", "h5", "h6",
    "header", "footer", "address", "main",
    "p", "hr", "pre", "blockquote", "ol", "ul", "li", "dl", "dt", "dd",
    "figure", "figcaption", "div",
    "a", "em", "strong", "small", "s", "cite", "q", "dfn", "abbr", "ruby",
    "rt", "rp", "data", "time", "code", "kbd", "samp", "sub", "sup", "i",
    "b", "u", "mark", "bdi", "bdo", "span", "br", "wbr",
    "ins", "del",
    "picture", "source", "img", "iframe", "embed", "object", "param",
    "video", "audio", "trackEl", "map", "area",
    "table", "caption", "colgroup", "col", "tbody", "thead", "tfoot",
    "tr", "td", "th",
    "form", "label", "input", "button", "select", "datalist", "optgroup",
    "option", "textarea", "output", "progress", "meter", "fieldset", "legend",
    "details", "summary", "dialog",
    "script", "noscript", "template", "slot", "canvas",

    "svg", "g", "defs", "desc", "title", "symbol", "use",
    "image", "switchEl",
    "path", "rect", "circle", "ellipse", "line", "polyline", "polygon",
    "text", "tspan", "textPath",
    "marker", "pattern", "mask", "clipPath",
    "linearGradient", "radialGradient", "stopEl",
    "filter", "feBlend", "feColorMatrix", "feComponentTransfer", "feComposite",
    "feConvolveMatrix", "feDiffuseLighting", "feDisplacementMap", "feDistantLight",
    "feDropShadow", "feFlood", "feFuncA", "feFuncB", "feFuncG", "feFuncR",
    "feGaussianBlur", "feImage", "feMerge", "feMergeNode", "feMorphology",
    "feOffset", "fePointLight", "feSpecularLighting", "feSpotLight", "feTile",
    "feTurbulence",
    "foreignObject", "view", "animate", "animateMotion", "animateTransform",
    "set", "mpath",

    "math", "maction", "maligngroup", "malignmark", "menclose", "merror",
    "mfenced", "mfrac", "mglyph", "mi", "mlabeledtr", "mlongdiv", "mmultiscripts",
    "mn", "mo", "mover", "mpadded", "mphantom", "mroot", "mrow", "ms",
    "mscarries", "mscarry", "msgroup", "msline", "mspace", "msqrt", "msrow",
    "mstack", "mstyle", "msub", "msubsup", "msup", "mtable", "mtd", "mtext",
    "mtr", "munder", "munderover", "semantics", "annotation", "annotation-xml"
] as const;